#!/bin/csh -f
#
# USAGE: custom_recon01.ss  <subj1_id>  <subj2_id> ... <subjn_id>
#
# VAV 4/14/18 adapted from reconstruct.ss
# TODO: put in some error checks for file non-existence that will return script
# TODO: insert flags to turn on/off steps...I think this requires some arg parsing though?

######################################################################
set root="/mnt/neurocube/local/serenceslab/vy/FSDAT/"

#Create directory stucture and convert DICOMs for each subject:
#foreach subj ($argv)

set subj = $argv[1]
set ar2 = $argv[2]
set ar3 = $argv[3]
set ar4 = $argv[4]

echo "You set options: $argv[2] $argv[3] $argv[4]"

if ( ! -e $SUBJECTS_DIR$subj/mri/orig.mgz ) then
    # try to convert the .nii into the .mgz
    if ( ! -e "$root/RAW/$subj/NII/${subj}_TAL.nii" ) then
        cp "/mnt/neurocube/local/serenceslab/retBV/${subj}2/Anat/talwskull/${subj}_TAL.nii.gz" "$root/RAW/$subj/NII/${subj}_TAL.nii.gz"
    endif
    mri_convert "$root/RAW/$subj/NII/${subj}_TAL.nii.gz" "$root/ANAT/$subj/mri/orig.mgz"
    cp "$root/ANAT/$subj/mri/orig.mgz" "$root/ANAT/$subj/mri/orig/001.mgz"
    cp "$root/ANAT/$subj/mri/orig.mgz" "$root/ANAT/$subj/mri/rawavg.mgz" # needed for auto-recon3
    echo "Converted ${subj}_TAL.nii.gz to orig.mgz!"
endif

if ( ! -e $SUBJECTS_DIR$subj/mri/brainmask.mgz ) then
    recon-all -autorecon1 -nomotioncor -subjid $subj
#        cd "$SUBJECTS_DIR$subj/mri/"
    # separating out autorecon1 commands with custom flags for a nii created from a BV TAL
#        mri_nu_correct.mni --i orig.mgz --o nu.mgz --n 2
#        mri_normalize -g 1 -mprage nu.mgz T1.mgz
#        cp nu.mgz brainmask.mgz
#        cd $SUBJECTS_DIR
else
    echo "Skipping autorecon1 steps..."
endif

# now do the rest of it!
if ( $ar2 == "autorecon2" ) then
    recon-all -autorecon2 -subjid $subj
else
    echo "Skipping autorecon2"
endif
if ( $ar3 == "autorecon3" ) then
    recon-all -autorecon3 -subjid $subj
else
    echo "Skipping autorecon3"
endif
if ( $ar4 == "hippo" ) then
    echo "SEGMENTING HIPPOCAMPUS"
    recon-all -hippocampal-subfields-T1 -subjid $subj
endif

#end
	

