#!/bin/bash
#
# This will take the nii output of the BV NIFTI convert tool, and reorient
# the image. I'm checking the output in fslview_deprecated, which may not
# be a perfect tool...
# 
# Synopsis
#     reorient_bvnii -s <subj_id>
#
# Required Arguments
#     -s <subj_id>
#
# VAV created 4/14/18. vyaivo@ucsd.edu

## DEBUG
#set -x;

#### default arguments
root="/mnt/neurocube/local/serenceslab/retBV"

#### parse arguments

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -s) subj="$2"; shift 2;;

        -*) echo "unknown option: $1" >&2; exit 1;;
        *) args+="$1"; shift 1;;
    esac
done

# check for file existence
path2tal="$root/$subj/Anat/talwskull"
tal="$path2tal/${subj}_skull_TAL.nii"
if [ ! -f $tal ]; then
    echo "ERROR: $tal does not exist!"
    echo "Run the NIFTI converter plugin in BV (BV TAL --> NII checkbox only) to convert."
    exit 1;
fi

### ACTUAL CONVERSION STEPS ###

# standard image view in fslview
# otherwise it shows images in scanner order
echo "Reorienting images to standard view..."
fslreorient2std $tal "$path2tal/${subj}_reorient.nii"

echo "Flipping dimensions..."
fslswapdim "$path2tal/${subj}_reorient.nii.gz" x -y z "$path2tal/${subj}_swapDim.nii"
cp "$path2tal/${subj}_swapDim.nii.gz" "$path2tal/${subj}_relabeled.nii.gz"

echo "Relabeling dimensions..."
sform=$(fslorient -getsform "$path2tal/${subj}_relabeled.nii.gz")
echo $sform
echo "becomes new sform"
# split this into array elements
IFS=' ' read -a arraysform <<< "$sform"
arraysform[0]=$((${arraysform[0]} * -1))
arraysform[5]=$((${arraysform[5]} * -1))
echo "${arraysform[@]}"

fslorient -setsform "${arraysform[@]}" "$path2tal/${subj}_relabeled.nii.gz"

fslorient -setqform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 "$path2tal/${subj}_relabeled.nii.gz"
#fslorient -setqform -1 0 0 0 0 -1 0 1 0 0 0 0 "$path2tal/${subj}_relabeled.nii.gz"

#fslorient -copysform2qform "$path2tal/${subj}_relabeled.nii.gz"
cp "$path2tal/${subj}_relabeled.nii.gz" "$path2tal/${subj:0:2}_TAL.nii.gz"

echo "Done! Please check the results in $path2tal/${subj:0:2}_TAL.nii.gz"

# end the script
exit
